# Deployment to a production environment is kicked off manually. This actually
# runs two deployment, one is to remove the canary pods if it exists and the
# other deploys to production.
production:
  production_environment: true
  required_contexts: ["build"]
  environment: production
  description: 'Production'
  payload:
    value_files: ["./config/production.yml"]
    # Remove the canary deployment if it exists when doing a full prod deploy.
    remove_canary: true
    release: production-myapp
    namespace: kkushal
    track: stable
    values:
      replicaCount: 1
